### ISSUE TITLE
it´s possible to run this on realtime?

### ISSUE THREAD

**Issue by ejtraderPlugins** [cedrickchee/rnnoise-nodejs#1]
2 questions 
1 its possible to run this on realtime using a mic input?
2 its possible to training with this library?

**Comment by falconhoster** [comment]
How did you manage to install this package? I tried everything but couldn't install it.

**Comment by cedrickchee** [comment]
This library is essential a thin wrapper around rnnoise. So, to answer your questions:

1) No. I have tried in Node.js by piping audio stream from mic input to the rnnoise C++ model and it doesn't work. The model was not designed to handle realtime denoising. The latency is higher than the range recommended to be considered realtime (read the paper to learn more).
2) I think it's possible to retrain the model. The paper did mentioned the datasets that they used for training the model. We need that to retrain the model using the Python stack that they used. Whether we can reproduce their results is unknown to me. Please read the paper to find out. To be clear, this library doesn't handle training.

**Comment by cedrickchee** [comment]
I'm closing this issue. If you have further questions, please open a new issue.
